---
- name: Output frpc version
  debug:
    msg: '{{ frpc.stdout|trim if frpc.stdout is defined else "Not Installed" }}'
  when:
  - install_frpc

- name: Output frps version
  debug:
    msg: '{{ frps.stdout|trim if frps.stdout is defined else "Not Installed" }}'
  when:
  - install_frps

- name: Check frp latest version
  uri:
    url: https://api.github.com/repos/fatedier/frp/releases/latest
  register: frp_version_latest
  when: frp_version is not defined

- name: Set frp latest version
  set_fact:
    frp_version: '{{ frp_version_latest.json.name.replace("v", "") }}'
  when: frp_version is not defined

- name: Check frp outdated
  set_fact:
    frpc_outdated: '{{ install_frpc and (frpc.stdout is not defined or frpc.stdout|trim != frp_version) }}'
    frps_outdated: '{{ install_frps and (frps.stdout is not defined or frps.stdout|trim != frp_version) }}'
