---
- name: Output frpc version
  debug:
    msg: '{{ frpc.stdout|trim if frpc.stdout is defined else "Not Installed" }}'
  when:
  - frpc_install

- name: Output frps version
  debug:
    msg: '{{ frps.stdout|trim if frps.stdout is defined else "Not Installed" }}'
  when:
  - frps_install

- name: Set frp latest version
  set_fact:
    frp_version: '{{ frp_version_latest.json.name.replace("v", "") }}'
  when: frp_version == ""

- name: Check frp outdated
  set_fact:
    frpc_outdated: '{{ frpc_install and (frpc.stdout is not defined or frpc.stdout|trim != frp_version) }}'
    frps_outdated: '{{ frps_install and (frps.stdout is not defined or frps.stdout|trim != frp_version) }}'
