---
- name: Output frpc version
  debug:
    msg: '{{ frpc.stdout|trim if frpc.stdout is defined else "Not Installed" }}'
  when:
  - install_frpc

- name: Output frps version
  debug:
    msg: '{{ frps.stdout|trim if frps.stdout is defined else "Not Installed" }}'
  when:
  - install_frps

- name: Set facts
  set_fact:
    frpc_outdated: '{{ install_frpc and (frpc.stdout is not defined or frpc.stdout|trim != version) }}'
    frps_outdated: '{{ install_frps and (frps.stdout is not defined or frps.stdout|trim != version) }}'
