---
# Linux
- name: restart frpc
  become: yes
  systemd:
    name: '{{ frpc_service_name }}'
    state: restarted
  when: ansible_service_mgr == "systemd"

- name: restart frps
  become: yes
  systemd:
    name: '{{ frps_service_name }}'
    state: restarted
  when: ansible_service_mgr == "systemd"

# Windows
- name: win restart frpc
  win_service:
    name: '{{ frpc_service_name }}'
    state: restarted

- name: win restart frps
  win_service:
    name: '{{ frps_service_name }}'
    state: restarted

# OpenWrt
- name: uci commit
  uci:
    command: commit

- name: openwrt restart frpc
  service:
    name: frpc
    state: restarted
