---
- name: Include Windows variables
  include_vars: windows.yml

- name: Check {{ frp }} version
  win_command: '{{ frp_dir }}\{{ frp }}.exe --version'
  register: frp_version_installed
  changed_when: no
  failed_when: no

- name: Check frp latest version
  win_uri:
    url: https://api.github.com/repos/fatedier/frp/releases/latest
    # return_content is required even though we're using JSON only.
    # Note that uri module does not requrie this.
    return_content: yes
    proxy_url: '{{ frpc_http_proxy|default("") }}'
  register: frp_version_latest
  when: frp_version == ""

- name: frp info
  include_tasks: ../frp_info.yml

- name: Download frp
  win_get_url:
    url: '{{ frp_release_url }}'
    dest: '{{ frp_tmp_dir }}\{{ frp_release_name }}.{{ frp_release_ext }}'
    proxy_url: '{{ frpc_http_proxy|default("") }}'
  when: frp_outdated

- name: Unzip frp
  win_unzip:
    src: '{{ frp_tmp_dir }}\{{ frp_release_name }}.{{ frp_release_ext }}'
    dest: '{{ frp_tmp_dir }}'
    delete_archive: yes
  when: frp_outdated

- name: Include {{ frp }} installation
  include: install_frp.yml component={{ frp }}

- name: Include {{ frp }} configuration
  include: configure_frp.yml component={{ frp }}
