---
- name: Include Windows variables
  include_vars: windows.yml

- name: Check frpc version
  win_command: '{{ frp_dir }}\frpc.exe --version'
  register: frpc
  when: frpc_install
  changed_when: no
  failed_when: no

- name: Check frps version
  win_command: '{{ frp_dir }}\frps.exe --version'
  register: frps
  when: frps_install
  changed_when: no
  failed_when: no

- name: Check frp latest version
  win_uri:
    url: https://api.github.com/repos/fatedier/frp/releases/latest
    # return_content is required even though we're using JSON only.
    # Note that uri module does not requrie this.
    return_content: yes
    proxy_url: '{{ frpc_http_proxy|default("") }}'
  register: frp_version_latest
  when: frp_version == ""

- name: frp info
  include_tasks: ../frp_info.yml

- name: Download frp
  win_get_url:
    url: '{{ frp_release_url }}'
    dest: '{{ frp_tmp_dir }}\{{ frp_release_name }}.{{ frp_release_ext }}'
    proxy_url: '{{ frpc_http_proxy|default("") }}'
  when: frpc_outdated or frps_outdated

- name: Unzip frp
  win_unzip:
    src: '{{ frp_tmp_dir }}\{{ frp_release_name }}.{{ frp_release_ext }}'
    dest: '{{ frp_tmp_dir }}'
    delete_archive: yes
  when: frpc_outdated or frps_outdated

- name: Include frpc installation
  include: install_frp.yml component=frpc
  when: frpc_outdated

- name: Include frps installation
  include: install_frp.yml component=frps
  when: frps_outdated

- name: Include frpc configuration
  include: configure_frp.yml component=frpc
  when: frpc_install

- name: Include frps configuration
  include: configure_frp.yml component=frps
  when: frps_install
