---
- name: Include variables
  include_vars: windows.yml

- name: Check frpc version
  win_command: '{{ frp_dir }}\frpc.exe --version'
  register: frpc
  when: install_frpc
  changed_when: no
  failed_when: no

- name: Check frps version
  win_command: '{{ frp_dir }}\frps.exe --version'
  register: frps
  when: install_frps
  changed_when: no
  failed_when: no

- name: frp info
  include_tasks: ../frp_info.yml

- name: Download frp
  win_get_url:
    url: '{{ frp_release_url }}'
    dest: '{{ frp_tmp_dir }}\{{ frp_release_name }}.{{ frp_release_ext }}'
  when: frpc_outdated or frps_outdated

- name: Unzip frp
  win_unzip:
    src: '{{ frp_tmp_dir }}\{{ frp_release_name }}.{{ frp_release_ext }}'
    dest: '{{ frp_tmp_dir }}'
    delete_archive: yes
  when: frpc_outdated or frps_outdated

- name: Include frpc installation
  include: install_frp.yml component=frpc
  when: frpc_outdated

- name: Include frps installation
  include: install_frp.yml component=frps
  when: frps_outdated

- name: Include frpc configuration
  include: configure_frp.yml component=frpc
  when: configure_frpc

- name: Include frps configuration
  include: configure_frp.yml component=frps
  when: configure_frps
