---
- name: Install {{ component }} bin
  become: yes
  copy:
    remote_src: yes
    src: '{{ frp_tmp_dir }}/{{ frp_release_name }}/{{ item }}'
    dest: '{{ frp_bin_dir }}'
    mode: '0755'
  with_items:
  - '{{ component }}'

- name: Create frp config directory
  become: yes
  file:
    path: '{{ frp_config_dir }}'
    state: directory
    mode: '0755'

- name: Install {{ component }} config
  become: yes
  copy:
    remote_src: yes
    src: '{{ frp_tmp_dir }}/{{ frp_release_name }}/{{ item }}'
    dest: '{{ frp_config_dir }}'
    backup: yes
  with_items:
  - '{{ component }}.ini'
  - '{{ component }}_full.ini'

- name: Create systemd service directory
  become: yes
  file:
    path: '{{ frp_systemd_dir }}'
    state: directory

- name: Install {{ component }} systemd services
  become: yes
  copy:
    remote_src: yes
    src: '{{ frp_tmp_dir }}/{{ frp_release_name }}/{{ item }}'
    dest: '{{ frp_systemd_dir }}'
  with_items:
  - systemd/{{ component }}.service
  - systemd/{{ component }}@.service
