---
- name: Include Linux variables
  include_vars: linux.yml

- name: Check {{ frp }} version
  command: "{{ frp }} --version"
  register: frp_version_installed
  changed_when: no
  failed_when: no

- name: Check frp latest version
  uri:
    url: https://api.github.com/repos/fatedier/frp/releases/latest
  environment:
    https_proxy: '{{ frpc_http_proxy|default(omit) }}'
  register: frp_version_latest
  when: frp_version == ""

- name: frp info
  include_tasks: ../frp_info.yml

- name: Download frp
  unarchive:
    remote_src: yes
    src: "{{ frp_release_url }}"
    dest: "{{ frp_tmp_dir }}"
  environment:
    https_proxy: '{{ frpc_http_proxy|default(omit) }}'
  when: frp_outdated

- name: Include {{ frp }} installation
  include: install_frp.yml component={{ frp }}
  when: frp_outdated

- name: Include {{ frp }} configuration
  include: configure_frp.yml component={{ frp }}
